#!/usr/bin/env perl

use strict;
use warnings;

MAIN: {
	#INSERTION#;
}

1;

=head1 NAME

#FILE# - 

=head1 SYNOPSIS



=head1 DESCRIPTION



=head1 AUTHOR

#NAME#, C<shiranpasternak@gmail.com>

=head1 COPYRIGHT

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
